export const appIcons = {
    burger: require('../../assets/icons/burger.png'),
    home: require('../../assets/icons/home.png'),
    more: require('../../assets/icons/more.png'),
    profit: require('../../assets/icons/profit.png'),
    reload: require('../../assets/icons/reload.png'),
    next: require('../../assets/icons/next.png'),    
    cart: require('../../assets/icons/cart.png'),
    map: require('../../assets/icons/map.png'),
    burgerImage: require('../../assets/icons/burgerImage.png'),
    burgerImageOne: require('../../assets/icons/burgerImageOne.png'),
    reorder: require('../../assets/icons/reorder.png'),
    logo: require('../../assets/icons/logo.png'),
    logowide: require('../../assets/icons/logowide.png'),
    offerImageOne: require('../../assets/icons/offerimageOne.jpeg'),
    close: require('../../assets/icons/close.png'),
    carticon: require('../../assets/icons/carticon.png'),
}