export const screens = {
    mainTab: 'Main-Tab-Screen',
    homeTab: 'Home-Tab',
    developmentHome: 'Development-Home',
    offersTab: 'Offers-Tab',
    developmentOffers: 'Development-Offers',
    orderTab: 'Order-Tab',
    developmentOrder: 'Development-Order',
    reorderTab: 'Reorder-Tab',
    developmentReorder: 'Development-Reorder',
    moreTab: 'More-Tab',    
    moreTabMainScreen: 'More-Tab-Main-Screen',
    feedbackScreen: 'Feedback-Screen',
    cartScreen: 'Cart-Screen',
}